name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: 7.3
            phpunit: 8
          - php: 7.4
            phpunit: 8
          - php: 8.3
            phpunit: 9

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          version: ${{ matrix.phpunit }}
          php_version: ${{ matrix.php }}
